import { Shield, ArrowLeft } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

export default function PrivacyPolicy() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <button onClick={() => navigate(-1)}
        className="fixed left-4 z-30 w-11 h-11 rounded-full glass-card flex items-center justify-center"
        style={{ top: 'calc(env(safe-area-inset-top, 0px) + 0.75rem)' }}>
        <ArrowLeft className="w-4 h-4 text-foreground" />
      </button>
      <div className="max-w-2xl mx-auto px-4 py-12 pt-safe-12">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'hsl(35 95% 55% / 0.1)', border: '1px solid hsl(35 95% 55% / 0.25)' }}>
            <Shield className="w-5 h-5 text-amber-400" />
          </div>
          <div>
            <h1 className="font-heading text-2xl font-bold text-foreground">Privacy Policy</h1>
            <p className="text-xs text-muted-foreground">Last updated: August 2026</p>
          </div>
        </div>

        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">1. Overview</h2>
            <p>Scan Anything AI is a free AR visual discovery app that helps you identify and learn about objects in the physical world around you. Point your camera at anything — a plant, a rock, a gadget, a landmark — and Scan Anything AI uses AI vision to tell you what it is, share interesting facts, and help you build a personal collection of discoveries. We are committed to protecting your privacy and being transparent about how your data is used.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">2. Information We Collect</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><span className="text-foreground font-medium">Account info:</span> Your email address and display name when you create an account.</li>
              <li><span className="text-foreground font-medium">Discovery photos:</span> Images you capture or upload for AI identification.</li>
              <li><span className="text-foreground font-medium">Discovery data:</span> AI-generated names, categories, descriptions, and metadata for objects you choose to save.</li>
              <li><span className="text-foreground font-medium">AI conversations:</span> Questions you ask and answers you receive about your discoveries.</li>
              <li><span className="text-foreground font-medium">Progress data:</span> XP, level, streaks, achievements, and challenge progress.</li>
              <li><span className="text-foreground font-medium">Usage analytics:</span> Anonymous data about feature usage to help us improve the app.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">3. How We Use Your Data</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>To identify objects in your photos using AI vision analysis.</li>
              <li>To save your discoveries and organize them into collections.</li>
              <li>To answer your follow-up questions about objects you've discovered.</li>
              <li>To track your exploration progress, achievements, and streaks.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">4. Camera & Photos</h2>
            <p>The app requests camera and photo library access only when you initiate a discovery. Images are sent to our AI service for identification and stored in your collection only if you choose to save the discovery. You can delete any discovery or its photo at any time.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">5. AI Analysis</h2>
            <p>Object identification and descriptions are generated by AI and may not always be accurate. The AI processes your images to provide educational and curiosity-driven information about what you're looking at. This analysis is for personal learning and entertainment — not for professional, medical, safety, or financial decisions.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">6. Data Storage & Security</h2>
            <p>Your discovery data is stored securely and is private to your account. We do not sell your personal data to third parties. Your discoveries, collections, and AI conversations are visible only to you.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">7. Your Rights</h2>
            <p>You can delete individual discoveries, collections, and AI conversations at any time within the app. You may request full account deletion by contacting support.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">8. Children's Privacy</h2>
            <p>The app is not directed to children under 13 and we do not knowingly collect data from them.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">9. No Fees or Subscriptions</h2>
            <p>Scan Anything AI is completely free. There are no in-app purchases, subscriptions, or hidden fees. All features are available to all users at no cost.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">10. Changes to This Policy</h2>
            <p>We may update this policy from time to time. Continued use of the app constitutes acceptance of the updated policy.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">11. Contact</h2>
            <p>For privacy questions, please contact Base44 support.</p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-border/40">
          <Link to="/profile" className="text-amber-400 text-sm">← Back to Profile</Link>
        </div>
      </div>
    </div>
  );
}