import { FileText, ArrowLeft } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

export default function TermsOfUse() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <button onClick={() => navigate(-1)}
        className="fixed left-4 z-30 w-11 h-11 rounded-full glass-card flex items-center justify-center"
        style={{ top: 'calc(env(safe-area-inset-top, 0px) + 0.75rem)' }}>
        <ArrowLeft className="w-4 h-4 text-foreground" />
      </button>
      <div className="max-w-2xl mx-auto px-4 py-12 pt-safe-12">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'hsl(263 70% 58% / 0.1)', border: '1px solid hsl(263 70% 58% / 0.25)' }}>
            <FileText className="w-5 h-5 text-violet-400" />
          </div>
          <div>
            <h1 className="font-heading text-2xl font-bold text-foreground">Terms of Use</h1>
            <p className="text-xs text-muted-foreground">Last updated: August 2026</p>
          </div>
        </div>

        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>By using Scan Everything, you agree to these Terms of Use. If you do not agree, please do not use the app.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">2. Free Service</h2>
            <p>Scan Everything is provided free of charge. There are no subscriptions, in-app purchases, or fees. All features are available to all users at no cost. The service is provided "as is" without warranties of any kind.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">3. User Content</h2>
            <p>You retain ownership of content you submit, including scan photos, vault items, sell listings, and community deal posts. By posting community deals, you grant other users the right to view that content within the app.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">4. Acceptable Use</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Do not post false, misleading, or fraudulent deal information.</li>
              <li>Do not upload content that infringes others' intellectual property.</li>
              <li>Do not use the app for illegal activities or spam.</li>
              <li>Do not attempt to disrupt or compromise the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">5. AI-Generated Estimates</h2>
            <p>Item identification, price estimates, and value assessments are generated by AI and may be inaccurate. Always conduct your own research before making purchasing or selling decisions. We are not liable for financial losses based on app estimates.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">6. Community Deals</h2>
            <p>Community-sourced deals reflect individual user findings. We do not verify the accuracy of every post. Use discretion when acting on community-shared information.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">7. Third-Party Marketplaces</h2>
            <p>The app references prices from third-party marketplaces (eBay, Amazon, etc.) for informational purposes. We are not affiliated with these services and are not responsible for their content or transactions.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">8. Limitation of Liability</h2>
            <p>The app is provided free of charge. To the maximum extent permitted by law, we are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the app.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">9. Account Termination</h2>
            <p>We may suspend or terminate accounts that violate these terms. You may delete your account and data at any time by contacting support.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">10. Changes to Terms</h2>
            <p>We may update these terms periodically. Continued use after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-base font-heading font-bold text-foreground mb-2">11. Contact</h2>
            <p>For questions about these terms, please contact Base44 support.</p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-border/40">
          <Link to="/profile" className="text-cyan-400 text-sm">← Back to Profile</Link>
        </div>
      </div>
    </div>
  );
}